spring:
  application:
    name: lottery

logging:
  file: logs/${spring.application.name}/${spring.application.name}.log
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'